DROP TABLE news;

CREATE TABLE publisher (
    publisher_id       NUMBER(19)              GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name              VARCHAR2(256)           NOT NULL,

    PRIMARY KEY(publisher_id)
);


CREATE TABLE news (
    news_id       NUMBER(19)              GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title         VARCHAR2(256)           NOT NULL,
    content       CLOB                    NOT NULL,
    publisher_id  NUMBER(19)              NOT NULL, 

    PRIMARY KEY(news_id),
    FOREIGN KEY(publisher_id) REFERENCES publisher(publisher_id)
);

